### ISSUE TITLE
Video controls aren't visible on safari

### ISSUE THREAD

**Issue by nullTheCoder** [lighttube-org/LTPlayer#3]
Video controls aren't visible on safari, they can be interacted with, however they appear to be invisible.

Safari Version 17.4.1 (19618.1.15.11.14)
MacOS 14.4.1 (23E224)

**Comment by kuylar** [comment]
Looks like a rendering bug due to `z-index`, as segments are visible. Setting `z-index: 0` on the `<video>` seems to fix it.

I love safari
